os: linux
language: android
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - extra-google-goole_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-27
  - sys-img-armeabi-v7a-google_apis-27
jdk: oraclejdk8
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid
before_script:
- wget http://services.gradle.org/distributions/gradle-4.1-all.zip
- unzip -qq gradle-4.1-all.zip
- export GRADLE_HOME=$PWD/gradle-4.1
- export PATH=$GRADLE_HOME/bin:$PATH
- git clone https://github.com/flutter/flutter.git -b beta --depth 1
script:
- "./flutter/bin/flutter -v build apk"
cache:
  directories:
  - "$HOME/.pub-cache"
before_install:
- openssl aes-256-cbc -K $encrypted_f8bfbe1ece13_key -iv $encrypted_f8bfbe1ece13_iv
  -in key.properties.enc -out ./android/key.properties -d
- openssl aes-256-cbc -K $encrypted_f8bfbe1ece13_key -iv $encrypted_f8bfbe1ece13_iv
  -in terreciel.jks.enc -out terreciel.jks -d
